### PR TITLE
Fix resolve action

### LINKED ISSUE #1233: Choose item from search does not generate code sometimes

### PR DESCRIPTION
**Pull request by jperl**
Resolves #1233

### CODE REVIEW

File: recorder/src/resolveElementAction.ts [hunk 1]
```diff
@@ -55,105 +51,104 @@ export const KEYS_TO_TRACK_FOR_NON_INPUT = new Set([
...
+        "resolveAction: use selector from visible mousedown",
+        mouseDown.selector,
+        mouseDown.target
       );
-      return { action, selector: lastReceivedAction.selector };
+      return { action, selector: mouseDown.selector, time: event.time };
     }
+  }
 
-    debug("resolveAction: skip action on invisible target");
```
Comment (jperl) [inline recorder/src/resolveElementAction.ts:138]: Add a test for this I just broke this logic in this PR 😅
