### PR TITLE
Run tests with CLI

### LINKED ISSUE #1182: Run tests with CLI
Poll for the response then exit with a failing code if the tests fail.

This will make it easy to run tests in "Name your CI".

### PR DESCRIPTION
**Pull request by flaurida**
* resolves #1182

### CODE REVIEW

File: qawolf/src/cli/index.ts [hunk 1]
```diff
@@ -23,3 +25,6 @@ program.allowUnknownOption(false);
 export const runCli = (
   argv: string[] = process.argv
 ): Promise<program.CommanderStatic> => program.parseAsync(argv);
+
+// TODO: remove this
```
Comment (jperl) [inline qawolf/src/cli/index.ts:29]: ?

Comment (flaurida) [reply qawolf/src/cli/index.ts:29]: let me remove the call thank you

File: qawolf/src/cli/runTests.ts [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+  triggerId,
+  wait,
+}: RunTests): Promise<void> {
+  console.log(bold(`\n🐺  Run QA Wolf tests for trigger ${triggerId}`));
+
+  ensureApiKey();
+  const suiteId = await createSuite({ env, triggerId });
+
+  if (!wait) {
+    console.log("🐺 complete, do not wait for tests to run");
```
Comment (jperl) [inline qawolf/src/cli/runTests.ts:93]: I would remove the log

**Review by jperl — APPROVED** [review]
