### PR TITLE
Retry runs with ERR_CONNECTION_REFUSED error

### LINKED ISSUE #1062: Retry ERR_CONNECTION_REFUSED errors
Every ~1/5000 runs, the Azure container might have intermittent connectivity issues (bad rack, co-tenants, etc).

Even though it's rare, it is annoying to find a run failed a navigation if it has nothing to do with your site.

Store and retry ERR_CONNECTION_REFUSED once. We can expand this list over time.

### PR DESCRIPTION
**Pull request by jperl**
Resolves #1062

### CODE REVIEW

File: app/server/resolvers/runner.ts [hunk 1]
```diff
@@ -168,8 +168,8 @@ export const updateRunnerResolver = async (
 
   let runId = runner.run_id;
 
-  // assign the runner if there is a pending test or run
-  if (!runner.run_id && !runner.test_id) {
+  // assign the runner if it's session has not been
```
Comment (flaurida) [inline app/server/resolvers/runner.ts:171]: its

**Review by flaurida — APPROVED** [review]
